### ISSUE TITLE
【建议提交】【1.4.2】【pom中的scope感觉不太妥当】

### ISSUE THREAD

**Issue by iblader** [BeardedManZhao/mathematical-expression#16]
这个包在编译和运行的时候都要用到，它的scope应该是默认才对，不应该是Provided：
<dependency>
            <groupId>io.github.BeardedManZhao</groupId>
            <artifactId>varFormatter</artifactId>
            <version>1.0.4</version>
            _<scope>provided</scope>_
</dependency>

**Comment by BeardedManZhao** [comment]
感谢您的反馈，起初是打算使用默认的，但是此库并不是必须库，为了减少了打包的依赖，便将此库`scope`设为了 `Provided` ，若您感觉此举不妥当，我们会尝试去将`scope`做为 默认。

**Comment by BeardedManZhao** [comment]
## 回复

如果没有使用到 [执行过程流程图](https://github.com/BeardedManZhao/mathematical-expression/blob/main/README-Chinese.md#%E8%AF%A6%E7%BB%86%E7%9A%84%E6%89%A7%E8%A1%8C%E8%AE%B0%E5%BD%95) 功能，此库可以省略，在编译期和运行期中将不会出现异常。

`scope = Provided` 可以避免库在任何情况下都强制导入的问题

> 测试版本：1.4.2

## 测试效果

### maven 

> 在这里由于我们没有使用到 [执行过程流程图](https://github.com/BeardedManZhao/mathematical-expression/blob/main/README-Chinese.md#%E8%AF%A6%E7%BB%86%E7%9A%84%E6%89%A7%E8%A1%8C%E8%AE%B0%E5%BD%95) 功能，因此也没有导入 `varFormatter` 库。

```xml
    <dependencies>
        <!-- Binding using the adapter of log4j2 -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.20.0</version>
            <!--<scope>provided</scope>-->
        </dependency>

        <!-- Log4j2 log facade -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.20.0</version>
            <!--<scope>provided</scope>-->
        </dependency>

        <!-- Log4j2 log real surface -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.20.0</version>
            <!--<scope>provided</scope>-->
        </dependency>

        <dependency>
            <groupId>io.github.BeardedManZhao</groupId>
            <artifactId>mathematical-expression</artifactId>
            <version>1.4.2</version>
        </dependency>
    </dependencies>
```

### 代码

```java
    public static void main(String[] args) {
        Mathematical_Expression.Options.setUseCache(true);
        final CompileCalculation instance = (CompileCalculation) Mathematical_Expression.getInstance(Mathematical_Expression.prefixExpressionOperation);
        final PrefixExpression compile1 = (PrefixExpression) instance.compile("1+30", true);
        final PrefixExpression compile2 = (PrefixExpression) instance.compileBigDecimal("1+30", true);
        System.out.println(compile1.calculationCache(false));
        System.out.println(compile2.calculationBigDecimalsCache(false));
    }
```

### 执行结果

```
CalculationNumberResults{result=31.0, source='prefixExpressionOperation'}
CalculationNumberResults{result=31.0, source='prefixExpressionOperation'}
```

**Comment by iblader** [comment]
新建一个项目，依赖于1.4.2，但是不配置依赖于varFormatter，使用项目说明中的代码做简单的修改：
```
public static void main(String[] args) throws WrongFormat {
        final Calculation instance = Mathematical_Expression.getInstance(
                Mathematical_Expression.bracketsCalculation2
        );
        System.out.println(instance.calculation("(1+2)*3"));
    }
```
编译没有问题，但是执行的时候会出现以下异常：
```
Exception in thread "main" java.lang.NoClassDefFoundError: top/lingyuzhao/varFormatter/utils/DataObj
	at io.github.beardedManZhao.mathematicalExpression.core.Mathematical_Expression$1.getInstance(Mathematical_Expression.java:31)
	at io.github.beardedManZhao.mathematicalExpression.core.Mathematical_Expression.getInstance(Mathematical_Expression.java:331)
	at io.github.beardedManZhao.mathematicalExpression.core.Mathematical_Expression.getInstance(Mathematical_Expression.java:86)
	at kain.mavenproject3.MAIN.main(MAIN.java:14)
```
从开发者的直觉逻辑，这个代码并没有使用执行过程流程图，而是直接进行了计算和结果输出，但是却会发生CNF的异常，此时的varFormatter变成了必选项而非可选项，与说明文档中的“可选”感觉是有所不一致。

**Comment by iblader** [comment]
更好的方式可能可以将执行过程的逻辑转移，比如这样：

```
public static void main(String[] args) throws WrongFormat {
        final Calculation instance = Mathematical_Expression.getInstance(
                Mathematical_Expression.bracketsCalculation2
        );
        System.out.println(instance.calculation("(1+2)*3"));
        //以上均不依赖varFormatter
        Explainer.explain(instance); //Explainer 在varFormatter包中
    }
```

**Comment by BeardedManZhao** [comment]
确实复现了问题所在，支持 explain 操作的计算组件的获取时 若不包含 varFormatter 库都会出现此异常，这与日常的测试有出入，这并不是我们期望的，此问题一直被忽略，这算是一个 bug，感谢您的发现并反馈，我们决定将此问题的修复工作立刻开展，下一版本将修复此问题！感谢您的反馈与回复！
